name: Upload Python Package

on:
  push:
    branches: [master]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-24.04,
            ubuntu-24.04-arm,
          ]
        py: ["3.10-dev", "3.11-dev", "3.12-dev", "3.13-dev", "3.14-dev"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      # - name: Install Python development headers
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y python3-dev build-essential
  

      - name: Build release distributions
        run: |
          pip install --user pipx
          pip install Cython
          pipx ensurepath
          pipx install poetry
          poetry install --no-interaction --no-root
          make build_lib OS=${{ matrix.os }}
          poetry build --format wheel

      - name: Upload distributions
        uses: actions/upload-artifact@v6
        with:
          name: release-dist-${{ matrix.os }}-${{ matrix.py }}
          path: dist/
          
  release-build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [ 
            macos-15,
            macos-15-intel,
          ]
        py: ["3.10-dev", "3.11-dev", "3.12-dev", "3.13-dev", "3.14-dev"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Build release distributions
        run: |
          pip install --user pipx
          pip install Cython
          pipx ensurepath
          pipx install poetry
          poetry install --no-interaction --no-root
          make build_lib OS=${{ matrix.os }}
          poetry build --format wheel

      - name: Upload distributions
        uses: actions/upload-artifact@v6
        with:
          name: release-dist-${{ matrix.os }}-${{ matrix.py }}
          path: dist/

  release-build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            windows-latest,
            windows-11-arm,  
          ]
        py: ["3.10-dev", "3.11-dev", "3.12-dev", "3.13-dev", "3.14-dev"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Build release distributions
        run: |
          pip install --user pipx
          pip install Cython
          pipx ensurepath
          pipx install poetry
          poetry install --no-interaction --no-root
          make build_lib OS=${{ matrix.os }}
          poetry build --format wheel

      - name: Upload distributions
        uses: actions/upload-artifact@v6
        with:
          name: release-dist-${{ matrix.os }}-${{ matrix.py }}
          path: dist/


  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build-linux
      - release-build-macos
      - release-build-windows
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v6
        with:
          path: dist/

      - name: List Dists
        run: ls -R dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
